// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "1a1cfe82-9e49-44c9-a45c-be6b096ac747");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1639938081);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1639938056);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1639938055);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{5f7a3184-5c39-4381-8f4c-4779d1e993ce}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1639938051);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 121);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8e492e6a-675b-4abe-99f6-bfdab00a8eb4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1639938055);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1639938058155");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1639959658155");
user_pref("browser.search.region", "GB");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20211216190150");
user_pref("browser.startup.homepage_override.mstone", "96.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1639938054);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"developer-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"profiler-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1639938054954");
user_pref("distribution.iniFile.exists.appversion", "96.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "GB");
user_pref("dom.push.userAgentID", "e47c300b051b4c468b2f651c677cc152");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 34);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20211216190150");
user_pref("extensions.lastAppVersion", "96.0");
user_pref("extensions.lastPlatformVersion", "96.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1c866918-5d71-4d3d-90bb-e3e1df10f6eb\",\"formautofill@mozilla.org\":\"f4a8d1e8-9cd9-4e95-a5e3-ca67e2822ab4\",\"pictureinpicture@mozilla.org\":\"87c323de-d691-4f1e-bf5c-1cc28cf3240a\",\"proxy-failover@mozilla.com\":\"29d13279-cfae-4c07-92eb-dcd559a33e8f\",\"screenshots@mozilla.org\":\"20acf909-4dbe-452c-b82f-a8331fac9c20\",\"webcompat-reporter@mozilla.org\":\"3b8b5d29-cce3-4510-91b1-6007274312f3\",\"webcompat@mozilla.org\":\"eba5db29-06e4-4ec1-81dc-94c3b0fa7038\",\"addons-search-detection@mozilla.com\":\"47cfa54f-f4cd-44bd-864a-41f420726ce7\",\"google@search.mozilla.org\":\"c5ff3472-2816-4ee4-9f59-5a1cc6c94cb9\",\"wikipedia@search.mozilla.org\":\"f4c8f795-aeef-43db-8de2-39ee8bc7b093\",\"bing@search.mozilla.org\":\"b7044495-8c92-4d9e-a5a7-19759ccac829\",\"ddg@search.mozilla.org\":\"f93adb4c-02a6-46a3-b84d-35ef7714a59e\",\"firefox-compact-dark@mozilla.org\":\"1056ffe7-7a6e-4e20-b482-489361468c77\",\"amazon@search.mozilla.org\":\"21110c98-edbe-418a-a932-2d38ec2f474d\",\"ebay@search.mozilla.org\":\"14e889d2-e37f-4926-af3b-1a3c2d851028\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1639938056);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "029f49c6-2492-4772-8bb8-630cedfbc5ca");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1639938048);
user_pref("toolkit.telemetry.cachedClientID", "853cb265-dcca-4d73-a15d-c79214328e3d");
user_pref("toolkit.telemetry.previousBuildID", "20211216190150");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
